# Mule Application Properties
# ---------------------------------------------------

# HTTP Configuration
http.port=8081
http.base.path=/api/v1
# Database Configuration (MySQL)
db.host=localhost
db.port=3306
db.user=root
db.password=securepass
db.database=orders_db
# JMS Configuration (ActiveMQ)
jms.brokerUrl=tcp://localhost:61616
jms.queue.orders=orders.queue
jms.topic.notifications=notifications.topic
# REST Backend Configuration
rest.api.url=https://jsonplaceholder.typicode.com
rest.api.timeout=5000
# SOAP Backend Configuration
ws.endpoint=http://www.dneonline.com/calculator.asmx
ws.wsdl=http://www.dneonline.com/calculator.asmx?wsdl
# Application Settings
app.env=DEV
transaction.timeout=10000
soapVersion=v1.2
app.version=1.2.3
truist.db2.url.check=${db2.url}
truist.missing.test=${missing.property.test}
wmq.mts.cipherSuite=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
jce.token.type=JKS
sql.db.url=jdbc:sqlserver://localhost:1433/mydbraks;encrypt=false;trustServerCertificate=false;
secure::db.password=![encryptedProdPassword]
